package main.java.authentication.json;

import main.java.authentication.json.JsonObject;

import java.util.Map;

public class Baseline implements JsonObject {
    //     variables that was changed
    //    the left variable represent the column name from masterops
    //    while the right variable represent the java variable name used
    //    private String Slot_ID/UTID = public String Slot_ID_UTID;
    //    private String Sold-To_Name = public String Sold_To_Name;
    //    private String Ship_Revenue_(Int_$) = public String Ship_Revenue_Int_$;
    //    private String Ship_Risk/Upside = public String Ship_Risk_Upside;
    //    private String Int._Ops_Ship_Readiness_Date = public String Int_Ops_Ship_Readiness_Date;
    //    private String New/Used = public String New_Used;
    //    private String Book_Risk/Upside = public String Book_Risk_Upside;
    //    private String Change_Request_# = public String Change_Request;
    //    private String Delivery_# = public String Delivery;
    //    private String Purchase_Order_# = public String Purchase_Order;
    //    private String Sold-To_ID = public String Sold_To_ID;

    public String Argo_ID;
    public String Plant;
    public Integer Build_Complete;
    public String Slot_Status;
    public String Plan_Product_Type;
    public String Build_Category;
    public String Ship_Revenue_Type;
    public String Sales_Order;
    public String Forecast_ID;
    public String Slot_ID_UTID;
    public String Sold_To_Name;
    public String Fab_Name;
    public String Secondary_Customer_Name;
    public String Product_Family;
    public String Build_Product;
    public String Forecast_Product;
    public String Product_PN;
    public Integer Committed_Ship_$;
    public Integer Ship_Revenue_Int_$;
    public String Ship_Risk_Upside;
    public String Ship_Risk_Reason;
    public String MRP_Date;
    public String Int_Ops_Ship_Readiness_Date;
    public String MFG_Commit_Date;
    public String Ship_Recog_Date;
    public String Hand_Off_Date_To_DE;
    public String Hand_Off_Date_Back_To_MFG;
    public String SAP_Customer_Req_Date;
    public String Slot_Request_Date;
    public String Div_Commit_Date;
    public Integer Delta_Days;
    public String Region;
    public String SO_Status;
    public String Caerus_PO_Qtr;
    public String Install_Start_Date;
    public Integer Cycle_Time_Days;
    public String Slot_Plan_Note;
    public String Comment_For_$_Change;
    public String Configuration_Note;
    public String Drop_Ship;
    public String MFG_Status;
    public Integer Quantity;
    public Integer RMA_Tool;
    public String New_Used;
    public String Core_Need_Date;
    public String Core_Arrival_Date;
    public String Refurb_Start_Date;
    public String Refurb_Complete_Date;
    public String Donor_Status;
    public String Core_UTID;
    public String Core_Notes;
    public String Fab_ID;
    public String PGI_Date;
    public String Flex_01;
    public String Flex_02;
    public String Flex_03;
    public String Flex_04;
    public String Build_Qtr;
    public String Ship_Qtr;
    public String Ship_Recog_Qtr;
    public String MFG_Site;
    public String Division;
    public String Holds;
    public String IncoTerms;
    public String Sales_Slot_Identifier;
    public String MS_Owner;
    public String BU;
    public String Book_Risk_Reason;
    public String Book_Risk_Upside;
    public String Caerus_Commit;
    public String Caerus_Description;
    public String Caerus_Product_Type;
    public String Change_Request;
    public String Delivery;
    public String Purchase_Order;
    public String SBU;
    public String Sales_Ops_Slot_Notes;
    public String Segment;
    public String Slot_Gap;
    public String Slot_Request_Qtr;
    public String Sold_To_ID;
    public String Standard_COGS;
    public String Created_By;
    public String Created_On;
    public String Changed_On;
    public String Created_Time;
    public String Changed_By;
    public String Last_Changed_Time;


    public Baseline(Map<String, Object> row) {
        this.Argo_ID = row.get("Argo ID") == null ? "" : (String) row.get("Argo ID");
        this.Plant = row.get("Plant") == null ? "" : (String) row.get("Plant");
        this.Build_Complete = (Integer) row.get("Build Complete");
        this.Slot_Status = row.get("Slot Status") == null ? "" : (String) row.get("Slot Status");
        this.Plan_Product_Type = row.get("Plan Product Type") == null ? "" : (String) row.get("Plan Product Type");
        this.Build_Category = row.get("Build Category") == null ? "" : (String) row.get("Build Category");
        this.Ship_Revenue_Type = row.get("Ship Revenue Type") == null ? "" : (String) row.get("Ship Revenue Type");
        this.Sales_Order = row.get("Sales Order") == null ? "" : (String) row.get("Sales Order");
        this.Forecast_ID = row.get("Forecast ID") == null ? "" : (String) row.get("Forecast ID");
        this.Slot_ID_UTID = row.get("Slot ID/UTID") == null ? "" : (String) row.get("Slot ID/UTID");
        this.Sold_To_Name = row.get("Sold-To Name") == null ? "" : (String) row.get("Sold-To Name");
        this.Fab_Name = row.get("Fab Name") == null ? "" : (String) row.get("Fab Name");
        this.Secondary_Customer_Name = row.get("Secondary Customer Name") == null ? "" : (String) row.get("Secondary Customer Name");
        this.Product_Family = row.get("Product Family") == null ? "" : (String) row.get("Product Family");
        this.Build_Product = row.get("Build Product") == null ? "" : (String) row.get("Build Product");
        this.Forecast_Product = row.get("Forecast Product") == null ? "" : (String) row.get("Forecast Product");
        this.Product_PN = row.get("Product PN") == null ? "" : (String) row.get("Product PN");
        this.Committed_Ship_$ = (Integer) row.get("Committed Ship $");
        this.Ship_Revenue_Int_$ = (Integer) row.get("Ship Revenue (Int $)");
        this.Ship_Risk_Upside = row.get("Ship Risk/Upside") == null ? "" : (String) row.get("Ship Risk/Upside");
        this.Ship_Risk_Reason = row.get("Ship Risk Reason") == null ? "" : (String) row.get("Ship Risk Reason");
        this.MRP_Date = row.get("MRP Date") == null ? "" : (String) row.get("MRP Date");
        this.Int_Ops_Ship_Readiness_Date = row.get("Int. Ops Ship Readiness Date") == null ? "" : (String) row.get("Int. Ops Ship Readiness Date");
        this.MFG_Commit_Date = row.get("MFG Commit Date") == null ? "" : (String) row.get("MFG Commit Date");
        this.Ship_Recog_Date = row.get("Ship Recog Date") == null ? "" : (String) row.get("Ship Recog Date");
        this.Hand_Off_Date_To_DE = row.get("Hand Off Date To DE") == null ? "" : (String) row.get("Hand Off Date To DE");
        this.Hand_Off_Date_Back_To_MFG = row.get("Hand Off Date Back To MFG") == null ? "" : (String) row.get("Hand Off Date Back To MFG");
        this.SAP_Customer_Req_Date = row.get("SAP Customer Req Date") == null ? "" : (String) row.get("SAP Customer Req Date");
        this.Slot_Request_Date = row.get("Slot Request Date") == null ? "" : (String) row.get("Slot Request Date");
        this.Div_Commit_Date = row.get("Div Commit Date") == null ? "" : (String) row.get("Div Commit Date");
        this.Delta_Days = row.get("Delta Days") == null ? null : (Integer) row.get("Delta Days");
        this.Region = row.get("Region") == null ? "" : (String) row.get("Region");
        this.SO_Status = row.get("SO Status") == null ? "" : (String) row.get("SO Status");
        this.Caerus_PO_Qtr = row.get("Caerus PO Qtr") == null ? "" : (String) row.get("Caerus PO Qtr");
        this.Install_Start_Date = row.get("Install Start Date") == null ? "" : (String) row.get("Install Start Date");
        this.Cycle_Time_Days = (Integer) row.get("Cycle Time Days");
        this.Slot_Plan_Note = row.get("Slot Plan Note") == null ? "" : (String) row.get("Slot Plan Note");
        this.Comment_For_$_Change = row.get("Comment For $ Change") == null ? "" : (String) row.get("Comment For $ Change");
        this.Configuration_Note = row.get("Configuration Note") == null ? "" : (String) row.get("Configuration Note");
        this.Drop_Ship = row.get("Drop Ship") == null ? "" : (String) row.get("Drop Ship");
        this.MFG_Status = row.get("MFG Status") == null ? "" : (String) row.get("MFG Status");
        this.Quantity = (Integer) row.get("Quantity");
        this.RMA_Tool = (Integer) row.get("RMA Tool");
        this.New_Used = (String) row.get("New/Used");
        this.Core_Need_Date = row.get("Core Need Date") == null ? "" : (String) row.get("Core Need Date");
        this.Core_Arrival_Date = row.get("Core Arrival Date") == null ? "" : (String) row.get("Core Arrival Date");
        this.Refurb_Start_Date = row.get("Refurb Start Date") == null ? "" : (String) row.get("Refurb Start Date");
        this.Refurb_Complete_Date = row.get("Refurb Complete Date") == null ? "" : (String) row.get("Refurb Complete Date");
        this.Donor_Status = row.get("Donor Status") == null ? "" : (String) row.get("Donor Status");
        this.Core_UTID = row.get("Core UTID") == null ? "" : (String) row.get("Core UTID");
        this.Core_Notes = row.get("Core Notes") == null ? "" : (String) row.get("Core Notes");
        this.Fab_ID = row.get("Fab ID") == null ? "" : (String) row.get("Fab ID");
        this.PGI_Date = row.get("PGI Date") == null ? "" : (String) row.get("PGI Date");
        this.Flex_01 = row.get("Flex 01") == null ? "" : (String) row.get("Flex 01");
        this.Flex_02 = row.get("Flex 02") == null ? "" : (String) row.get("Flex 02");
        this.Flex_03 = row.get("Flex 03") == null ? "" : (String) row.get("Flex 03");
        this.Flex_04 = row.get("Flex 04") == null ? "" : (String) row.get("Flex 04");
        this.Build_Qtr = row.get("Build Qtr") == null ? "" : (String) row.get("Build Qtr");
        this.Ship_Qtr = row.get("Ship Qtr") == null ? "" : (String) row.get("Ship Qtr");
        this.Ship_Recog_Qtr = row.get("Ship Recog Qtr") == null ? "" : (String) row.get("Ship Recog Qtr");
        this.MFG_Site = row.get("MFG Site") == null ? "" : (String) row.get("MFG Site");
        this.Division = row.get("Division") == null ? "" : (String) row.get("Division");
        this.Holds = row.get("Holds") == null ? "" : (String) row.get("Holds");
        this.IncoTerms = row.get("IncoTerms") == null ? "" : (String) row.get("IncoTerms");
        this.Sales_Slot_Identifier = row.get("Sales Slot Identifier") == null ? "" : (String) row.get("Sales Slot Identifier");
        this.MS_Owner = row.get("MS Owner") == null ? "" : (String) row.get("MS Owner");
        this.BU = row.get("BU") == null ? "" : (String) row.get("BU");
        this.Book_Risk_Reason = row.get("Book Risk Reason") == null ? "" : (String) row.get("Book Risk Reason");
        this.Book_Risk_Upside = row.get("Book Risk/Upside") == null ? "" : (String) row.get("Book Risk/Upside");
        this.Caerus_Commit = row.get("Caerus Commit") == null ? "" : (String) row.get("Caerus Commit");
        this.Caerus_Description = row.get("Caerus Description") == null ? "" : (String) row.get("Caerus Description");
        this.Caerus_Product_Type = row.get("Caerus Product Type") == null ? "" : (String) row.get("Caerus Product Type");
        this.Change_Request = row.get("Change Request #") == null ? "" : (String) row.get("Change Request #");
        this.Delivery = row.get("Delivery #") == null ? "" : (String) row.get("Delivery #");
        this.Purchase_Order = row.get("Purchase Order #") == null ? "" : (String) row.get("Purchase Order #");
        this.SBU = row.get("SBU") == null ? "" : (String) row.get("SBU");
        this.Sales_Ops_Slot_Notes = row.get("Sales Ops Slot Notes") == null ? "" : (String) row.get("Sales Ops Slot Notes");
        this.Segment = row.get("Segment") == null ? "" : (String) row.get("Segment");
        this.Slot_Gap = row.get("Slot Gap") == null ? "" : (String) row.get("Slot Gap");
        this.Slot_Request_Qtr = row.get("Slot Request Qtr") == null ? "" : (String) row.get("Slot Request Qtr");
        this.Sold_To_ID = row.get("Sold-To ID") == null ? "" : (String) row.get("Sold-To ID");
        this.Standard_COGS = row.get("Standard COGS") == null ? "" : (String) row.get("Standard COGS");
        this.Created_By = row.get("Created By") == null ? "" : (String) row.get("Created By");
        this.Created_On = row.get("Created On") == null ? "" : (String) row.get("Created On");
        this.Changed_On = row.get("Changed On") == null ? "" : (String) row.get("Changed On");
        this.Created_Time = row.get("Created Time") == null ? "" : (String) row.get("Created Time");
        this.Changed_By = row.get("Changed By") == null ? "" : (String) row.get("Changed By");
        this.Last_Changed_Time = row.get("Last Changed Time") == null ? "" : (String) row.get("Last Changed Time");
    }
}
