package main.java.algorithm;

import java.util.*;
import java.text.*;

import org.apache.commons.lang3.time.DateUtils;


public class JSONProduct{
    private Integer argoID;
    private Integer plant;
    private String buildComplete;
    private String slotStatus;
    private String planProductType;
    private String buildCategory;
    private String shipRevenueType;
    private Integer salesOrder;
    private String forecastID;
    private String slotID_UTID;
    private String soldToName;
    private String fabName;  
    private String secondaryCustomerName;
    private String productFamily;
    private String buildProduct;
    private String forecastProduct;
    private String productPN;
    private String committedShip$;
    private String shipRevenueInt$;
    private String shipRisk_Upside;
    private String shipRiskReason;
    private Date MRPDate;
    private Date intOpsShipReadinessDate;
    private Date MFGCommitDate;
    private Date shipRecogDate;
    private Date handOffDateToDE;
    private Date handOffDateBackToMFG;
    private Date SAPCustomerReqDate;
    private Date slotRequestDate;
    private Date divCommitDate;
    private Integer deltaDays;
    private String region;
    private String SOStatus;
    private String caerusPOQtr;
    private Date installStartDate;
    private Integer cycleTimeDays;
    private String slotPlanNote;
    private String commentFor$Change;
    private String configurationNote;
    private String dropShip;
    private String MFGStatus;
    private Integer quantity;
    private String RMATool;
    private String new_Used;
    private Date coreNeedDate;
    private Date coreArrivalDate;
    private Date refurbStartDate;
    private Date refurbCompleteDate;
    private String donorStatus;
    private String coreUTID;
    private String coreNotes;
    private String fabID;
    private Date PGIDate;
    private String flex01;
    private String flex02;
    private String flex03;
    private String flex04;
    private String buildQtr;
    private String shipQtr;
    private String shipRecogQtr;
    private String MFGSite;
    private String division;
    private String holds;
    private String incoTerms;
    private String salesSlotIdentifier;
    private String MSOwner;
    private String BU;
    private String bookRiskReason;
    private String bookRisk_Upside;
    private String caerusCommit;
    private String caerusDescription;
    private String caerusProductType;
    private Integer changeRequestNumber;
    private Integer deliveryNumber;
    private Integer purchaseOrderNumber;
    private String SBU;
    private String salesOpsSlotNotes;
    private String segment;
    private String slotGap;
    private String slotRequestQtr;
    private String soldToID;
    private String standardCOGS;
    private String createdBy;
    private Date createdOn;
    private Date changedOn;
    private Date createdTime;
    private String changedBy;
    private Date lastChangedTime;
}